### ISSUE TITLE
AU Linux kernel autumn 2016 запрос на проверку mutex Кравченко Дима

### ISSUE THREAD

**Issue by equivalence1** [equivalence1/au-linux-kernel-autumn-2016#8]
Привет! У меня опять особо ничего не получилось (тесты падают и там явно есть всякие race condition), но, вроде, что-то попытался написать

https://github.com/equivalence1/au-linux-kernel-autumn-2016/commit/9e32a237509773b2c79e34e2c457688a776beb30

**Comment by eabatalov** [comment]
Привет.
50% за старание и у тебя зачет автоматом :)
